[package]
name = "gitbutler-tauri"
version = "0.0.0"
edition = "2024"
authors = ["GitButler <gitbutler@gitbutler.com>"]
publish = false
rust-version = "1.89"

[lib]
doctest = false
crate-type = ["lib", "staticlib", "cdylib"]

[[bin]]
name = "gitbutler-tauri"
path = "src/main.rs"
test = false

[build-dependencies]
tauri-build = { version = "2.3.1", features = [] }

[dependencies]
anyhow.workspace = true
backtrace = { version = "0.3.76", optional = true }
console-subscriber = "0.5.0"
gix = { workspace = true, features = ["max-performance", "worktree-mutation" ] }
serde.workspace = true
serde_json = { workspace = true, features = ["arbitrary_precision"] }
tauri = { version = "^2.9.2", features = ["unstable"] }
tauri-plugin-dialog = "2.4.2"
tauri-plugin-fs = "2.4.2"
tauri-plugin-http = "2.5.4"
tauri-plugin-log = "2.7.1"
tauri-plugin-os = "2.3.2"
tauri-plugin-process = "2.3.1"
tauri-plugin-shell = "2.3.3"
tauri-plugin-single-instance = "2.3.6"
tauri-plugin-store = "2.4.1"
tauri-plugin-updater = "2.9.0"
tauri-plugin-window-state = "2.4.1"
tauri-plugin-clipboard-manager = "2.3.2"

parking_lot.workspace = true
log = "^0.4"
git2.workspace = true
# The features here optimize for performance.
tokio = { workspace = true, features = ["rt-multi-thread", "parking_lot"] }
tracing.workspace = true
tracing-appender = "0.2.3"
tracing-subscriber.workspace = true
tracing-forest = { version = "0.2.0" }
gitbutler-watcher.workspace = true
gitbutler-repo-actions.workspace = true
gitbutler-command-context.workspace = true
but-feedback.workspace = true
gitbutler-project.workspace = true
gitbutler-error.workspace = true
but-secret.workspace = true
gitbutler-id.workspace = true
but-broadcaster.workspace = true
but-db.workspace = true
but-settings.workspace = true
but-workspace.workspace = true
but-core.workspace = true
but-action.workspace = true
but-bot.workspace = true
but-api = { workspace = true, features = ["tauri"] }
but-claude.workspace = true
but-github.workspace = true
open = "5"
url = "2.5.4"
but-path.workspace = true
uuid.workspace = true
but = { workspace = true, optional = true }

[target.'cfg(target_os = "macos")'.dependencies]
tauri-plugin-trafficlights-positioner = { git = "https://github.com/gitbutlerapp/tauri-plugin-trafficlights-positioner", branch = "v2" }

[lints.clippy]
all = "deny"
perf = "deny"
correctness = "deny"

[features]
default = ["custom-protocol", "devtools"]
## A forwarding to all crates that have windows-specific adjustments for testing on non-Windows.
windows = []
## If enabled, we will pretend to be `but` when the binary filename is `but`.
builtin-but = ["dep:but", "but-action/builtin-but"]
devtools = ["tauri/devtools"]

# this feature is used for production builds where `devPath` points to the filesystem
# DO NOT remove this
custom-protocol = ["tauri/custom-protocol"]

error-context = ["dep:backtrace"]
